sudo: required
dist: trusty

services:
  - docker

language: python
python:
  - "3.5"
  - "3.6"

install:
  - pip install pipenv

script:
  - pipenv install --dev
  - pipenv run py.test -sv unittests.py livetests.py
